### ISSUE TITLE
NPC - Park Staff

### ISSUE THREAD

**Issue by pizzatree** [pizzatree/LD50#9]
Purchasable
On purchase park staff will spawn out of park maintenace building
Player must pick them up and place them for their AOE
park staff will not leave this region
Cleaners will clean poop out of this area
Pushers will attempt to remove geese from area
If a bonker bonks a Park Staff, they fly off screen and Wilhelm scream

**Comment by Gregathee** [comment]
Needs to be made purchasable and test bonkability
